classes_dict = {          
            "class_1": "aeroplane",
            "class_2": "apple",
            "class_3": "backpack",
            "class_4": "banana",
            "class_5": "baseball bat",
            "class_6": "baseball gloves",
            "class_7": "baton",
            "class_8": "bear",
            "class_9": "bed",
            "class_10": "bench",
            "class_11": "bike",
            "class_12": "bird",
            "class_13": "boat",
            "class_14": "book",
            "class_15": "bottle",
            "class_16": "bowl",
            "class_17": "broccoli",
            "class_18": "bus",
            "class_19": "cake",
            "class_20": "carrot",
            "class_21": "cat",
            "class_22": "chair",
            "class_23": "clock",
            "class_24": "cow",
            "class_25": "cup",
            "class_26": "dining table",
            "class_27": "dog",
            "class_28": "donut",
            "class_29": "elephant",
            "class_30": "fire hydrant",
            "class_31": "flashlight",
            "class_32": "fork",
            "class_33": "frisbee",
            "class_34": "giraffe",
            "class_35": "glove",
            "class_36": "hair dryer",
            "class_37": "hand bag",
            "class_38": "hand grenade",
            "class_39": "handheld metal detector",
            "class_40": "helmet",
            "class_41": "horse",
            "class_42": "hot dog",
            "class_43": "id card",
            "class_44": "inline skate",
            "class_45": "keyboard",
            "class_46": "kite",
            "class_47": "knife",
            "class_48": "laptop",
            "class_49": "microbus",
            "class_50": "microwave",
            "class_51": "motorcycle",
            "class_52": "mouse",
            "class_53": "mpv",
            "class_54": "orange",
            "class_55": "oven",
            "class_56": "padlock",
            "class_57": "parking meter",
            "class_58": "person",
            "class_59": "pickup car",
            "class_60": "pizza",
            "class_61": "potted plant",
            "class_62": "public car",
            "class_63": "refrigerator",
            "class_64": "remote",
            "class_65": "safety box",
            "class_66": "sandwich",
            "class_67": "scissors",
            "class_68": "sedan",
            "class_69": "sheep",
            "class_70": "sink",
            "class_71": "skateboard",
            "class_72": "ski",
            "class_73": "smartphone",
            "class_74": "smoke grenade",
            "class_75": "snowboard",
            "class_76": "sofa",
            "class_77": "spoon",
            "class_78": "sport car",
            "class_79": "sports ball",
            "class_80": "stop sign",
            "class_81": "stun gun",
            "class_82": "suitcase",
            "class_83": "surfboard",
            "class_84": "teddy bear",
            "class_85": "tennis racket",
            "class_86": "tie",
            "class_87": "toaster",
            "class_88": "toilet",
            "class_89": "toothbrush",
            "class_90": "traffic light",
            "class_91": "train",
            "class_92": "truck",
            "class_93": "tv monitor",
            "class_94": "umbrella",
            "class_95": "vase",
            "class_96": "vest",
            "class_97": "walkie talkie",
            "class_98": "wine glass",
            "class_99": "zebra",
            "class_100": "batik shirts",
            "class_101": "eyeglasses",
            "class_102": "polo shirt",
            "class_103": "t-shirt",
            "class_104": "shirt",
            "class_105": "jeans pants",
            "class_106": "jeans shorts",
            "class_107": "fabric pants",
            "class_108": "suit",
            "class_109": "shoes",
            "class_110": "wristwatch",
            "class_111": "hijab",
            "class_112": "bag",
            "class_113": "dress",
            "class_114": "hat",
            "class_115": "beret",
            "class_116": "bracelet",
            "class_117": "peci",
            "class_118": "ring",
            "class_119": "microphone",
            "class_120": "camera",
            "class_121": "necklace",
            "class_122": "bow ties",
            "class_123": "earrings",
            "class_124": "headset",
            "class_125": "sandal",
            "class_126": "mask",
            "class_127": "pen",
            "class_128": "guitar",
            "class_129": "sorban",
            "class_130": "sarung",
            "class_131": "skirt",
            "class_132": "jacket",
            "class_133": "blangkon"
}

color_mapping = {
            "red": [255, 0, 0],
            "green": [0, 255, 0],
            "blue": [0, 0, 255],
            "yellow": [255, 255, 0],
            "cyan": [0, 255, 255],
            "magenta": [255, 0, 255],
            "white": [255, 255, 255],
            "black": [0, 0, 0],
            # Add more color mappings as needed
        }

attb_add = [
            "class_1", "class_2", "class_3", "class_4", "class_5",
            "class_6", "class_7", "class_8", "class_9", "class_10",
            "class_11", "class_12", "class_13", "class_14", "class_15",
            "class_16", "class_17", "class_18", "class_19", "class_20",
            "class_21", "class_22", "class_23", "class_24", "class_25",
            "class_26", "class_27", "class_28", "class_29", "class_30",
            "class_31", "class_32", "class_33", "class_34", "class_35",
            "class_36", "class_37", "class_38", "class_39", "class_40",
            "class_41", "class_42", "class_43", "class_44", "class_45",
            "class_46", "class_47", "class_48", "class_49", "class_50",
            "class_51", "class_52", "class_53", "class_54", "class_55",
            "class_56", "class_57", "class_58", "class_59", "class_60",
            "class_61", "class_62", "class_63", "class_64", "class_65",
            "class_66", "class_67", "class_68", "class_69", "class_70",
            "class_71", "class_72", "class_73", "class_74", "class_75",
            "class_76", "class_77", "class_78", "class_79", "class_80",
            "class_81", "class_82", "class_83", "class_84", "class_85",
            "class_86", "class_87", "class_88", "class_89", "class_90",
            "class_91", "class_92", "class_93", "class_94", "class_95",
            "class_96", "class_97", "class_98", "class_99", "class_100",
            "class_101", "class_102", "class_103", "class_104", "class_105",
            "class_106", "class_107", "class_108", "class_109", "class_110",
            "class_111", "class_112", "class_113", "class_114", "class_115",
            "class_116", "class_117", "class_118", "class_119", "class_120",
            "class_121", "class_122", "class_123", "class_124", "class_125",
            "class_126", "class_127", "class_128", "class_129", "class_130",
            "class_131", "class_132", "class_133",
            # "class_134", "class_135"
        ]